# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 2015.1.dev362\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2015-03-09 06:03+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/notifications.py:304
msgid "Failed to construct notifier"
msgstr ""

#: keystone/notifications.py:389
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:606
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/catalog/core.py:62
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/catalog/core.py:66
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:71
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:77
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/common/openssl.py:93
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr ""

#: keystone/common/openssl.py:121
#, python-format
msgid "Failed to remove file %(file_path)r: %(error)s"
msgstr ""

#: keystone/common/utils.py:239
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/cache/core.py:100
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:99
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:185
msgid "Server error"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - "
"%(region_id)s."
msgstr ""

#: keystone/contrib/federation/idp.py:410
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr ""

#: keystone/contrib/oauth1/core.py:136
msgid "Cannot retrieve Authorization headers"
msgstr ""

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: keystone/openstack/common/service.py:268
msgid "Unhandled exception"
msgstr ""

#: keystone/resource/core.py:477
#, python-format
msgid ""
"Circular reference or a repeated entry found projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/resource/core.py:939
#, python-format
msgid ""
"Unexpected results in response for domain config - %(count)s responses, "
"first option is %(option)s, expected option %(expected)s"
msgstr ""

#: keystone/resource/backends/sql.py:102 keystone/resource/backends/sql.py:121
#, python-format
msgid ""
"Circular reference or a repeated entry found in projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/token/provider.py:292
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:226
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/providers/common.py:611
msgid "Failed to validate token"
msgstr ""

#: keystone/token/providers/pki.py:47
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/fernet/utils.py:38
#, python-format
msgid ""
"Either [fernet_tokens] key_repository does not exist or Keystone does not"
" have sufficient permission to access it: %s"
msgstr ""

#: keystone/token/providers/fernet/utils.py:79
msgid ""
"Failed to create [fernet_tokens] key_repository: either it already exists"
" or you don't have sufficient permissions to create it"
msgstr ""

