# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Bruno Cornec <bruno.cornec@hp.com>, 2014
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2015-03-09 06:03+0000\n"
"PO-Revision-Date: 2015-03-07 04:31+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/keystone/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: keystone/notifications.py:304
msgid "Failed to construct notifier"
msgstr "Échec de construction de la notification"

#: keystone/notifications.py:389
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr "Échec de l'envoi de la notification %(res_id)s %(event_type)s"

#: keystone/notifications.py:606
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr "Échec de l'envoi de la notification %(action)s %(event_type)s "

#: keystone/catalog/core.py:62
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr "Critère mal formé - %(url)r n'est pas une chaine de caractère"

#: keystone/catalog/core.py:66
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr "Noeud final incorrect %(url)s - clé inconnue %(keyerror)s"

#: keystone/catalog/core.py:71
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""
"Noeud final incorrect '%(url)s'. L'erreur suivante est survenue pendant la "
"substitution de chaine : %(typeerror)s"

#: keystone/catalog/core.py:77
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""
"Noeud final incorrect '%s - Format incomplet (un type de notification manque-"
"t-il ?)"

#: keystone/common/openssl.py:93
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr "La commande %(to_exec)s a retourné %(retcode)s- %(output)s"

#: keystone/common/openssl.py:121
#, python-format
msgid "Failed to remove file %(file_path)r: %(error)s"
msgstr "Échec de la suppression du fichier %(file_path)r: %(error)s"

#: keystone/common/utils.py:239
msgid ""
"Error setting up the debug environment. Verify that the option --debug-url "
"has the format <host>:<port> and that a debugger processes is listening on "
"that port."
msgstr ""
"Erreur de configuration de l'environnement de débogage. Vérifiez que "
"l'option --debug-url a le format <host>:<port> et que le processus de "
"débogage écoute sur ce port."

#: keystone/common/cache/core.py:100
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:99
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Impossible de s'attacher à %(host)s:%(port)s"

#: keystone/common/environment/eventlet_server.py:185
msgid "Server error"
msgstr "Erreur serveur"

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""
"Référence circulaire ou entrée dupliquée trouvée dans l'arbre de la région - "
"%(region_id)s."

#: keystone/contrib/federation/idp.py:410
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr "Erreur lors de la signature d'une assertion : %(reason)s"

#: keystone/contrib/oauth1/core.py:136
msgid "Cannot retrieve Authorization headers"
msgstr ""

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "dans l'appel en boucle de durée fixe"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: keystone/openstack/common/service.py:268
msgid "Unhandled exception"
msgstr "Exception non gérée"

#: keystone/resource/core.py:477
#, python-format
msgid ""
"Circular reference or a repeated entry found projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/resource/core.py:939
#, python-format
msgid ""
"Unexpected results in response for domain config - %(count)s responses, "
"first option is %(option)s, expected option %(expected)s"
msgstr ""

#: keystone/resource/backends/sql.py:102 keystone/resource/backends/sql.py:121
#, python-format
msgid ""
"Circular reference or a repeated entry found in projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/token/provider.py:292
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:226
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list from "
"backend.  Expected `list` type got `%(type)s`. Old revocation list data: "
"%(list)r"
msgstr ""

#: keystone/token/providers/common.py:611
msgid "Failed to validate token"
msgstr "Echec de validation du token"

#: keystone/token/providers/pki.py:47
msgid "Unable to sign token"
msgstr "Impossible de signer le jeton"

#: keystone/token/providers/fernet/utils.py:38
#, python-format
msgid ""
"Either [fernet_tokens] key_repository does not exist or Keystone does not "
"have sufficient permission to access it: %s"
msgstr ""

#: keystone/token/providers/fernet/utils.py:79
msgid ""
"Failed to create [fernet_tokens] key_repository: either it already exists or "
"you don't have sufficient permissions to create it"
msgstr ""
